---
# Source: csi-vxflexos/templates/controller.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vxflexos-controller
  namespace: vxflexos
---
# Source: csi-vxflexos/templates/node.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vxflexos-node
  namespace: vxflexos
---
# Source: csi-vxflexos/templates/driver-config-params.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vxflexos-config-params
  namespace: vxflexos
data:
  driver-config-params.yaml: |
    CSI_LOG_LEVEL: "debug"
    CSI_LOG_FORMAT: "TEXT"
---
# Source: csi-vxflexos/templates/controller.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vxflexos-controller
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
# below for snapshotter
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["volumegroup.storage.dell.com"]
    resources: ["dellcsivolumegroupsnapshots","dellcsivolumegroupsnapshots/status"]
    verbs: ["create", "list", "watch", "delete", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status","volumesnapshotcontents/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete", "update"]
---
# Source: csi-vxflexos/templates/node.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vxflexos-node
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumesclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["privileged"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
---
# Source: csi-vxflexos/templates/controller.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vxflexos-controller
subjects:
  - kind: ServiceAccount
    name: vxflexos-controller
    namespace: vxflexos
roleRef:
  kind: ClusterRole
  name: vxflexos-controller
  apiGroup: rbac.authorization.k8s.io
---
# Source: csi-vxflexos/templates/node.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vxflexos-node
subjects:
  - kind: ServiceAccount
    name: vxflexos-node
    namespace: vxflexos
roleRef:
  kind: ClusterRole
  name: vxflexos-node
  apiGroup: rbac.authorization.k8s.io
---
# Source: csi-vxflexos/templates/node.yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: vxflexos-node
  namespace: vxflexos

spec:
  selector:
    matchLabels:
      app: vxflexos-node
  template:
    metadata:
      labels:
        app: vxflexos-node
    spec:
      serviceAccount: vxflexos-node
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: false
      containers:

        - name: driver
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_ADMIN"]
          image: "amaas-eos-mw1.cec.lab.emc.com:5036/csi-vxflexos:v2.0-latest"
          imagePullPolicy: Always
          command: [ "/csi-vxflexos.sh" ]
          args:
            - "--array-config=/vxflexos-config/config"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_PRIVATE_MOUNT_DIR
              value: "/var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks"
            - name: X_CSI_ALLOW_RWO_MULTI_POD_ACCESS
              value: "true"
            - name: SSL_CERT_DIR
              value: /certs
            - name: X_CSI_HEALTH_MONITOR_ENABLED
              value: "false"
          volumeMounts:
            - name: driver-path
              mountPath: /var/lib/kubelet/plugins/vxflexos.emc.dell.com
            - name: volumedevices-path
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices
              mountPropagation: "Bidirectional"
            - name: pods-path
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: dev
              mountPath: /dev
            - name: vxflexos-config
              mountPath: /vxflexos-config
            - name: vxflexos-config-params
              mountPath: /vxflexos-config-params
        - name: registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --kubelet-registration-path=/var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock
          env:
            - name: ADDRESS
              value: /csi/csi_sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: driver-path
              mountPath: /csi
      initContainers:
        - name: sdc
          securityContext:
            privileged: true
          image: amaas-eos-mw1.cec.lab.emc.com:5044/container/sdc:3.6.0.354
          imagePullPolicy: Always
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MODE
              value: "config"
            - name: MDM
              valueFrom:
                secretKeyRef:
                  name: vxflexos-config
                  key: MDM
            - name: HOST_DRV_CFG_PATH
              value: /opt/emc/scaleio/sdc/bin
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: os-release
              mountPath: /host-os-release
            - name: sdc-storage
              mountPath: /storage
            - name: udev-d
              mountPath: /rules.d
            - name: scaleio-path-opt
              mountPath: /host_drv_cfg_path
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: driver-path
          hostPath:
            path: /var/lib/kubelet/plugins/vxflexos.emc.dell.com
            type: DirectoryOrCreate
        - name: volumedevices-path
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices
            type: DirectoryOrCreate
        - name: pods-path
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: scaleio-path-opt
          hostPath:
            path: /opt/emc/scaleio/sdc/bin
            type: DirectoryOrCreate
        - name: sdc-storage
          hostPath:
            path: /var/emc-scaleio
            type: DirectoryOrCreate
        - name: udev-d
          hostPath:
            path: /etc/udev/rules.d
            type: Directory
        - name: os-release
          hostPath:
            path: /etc/os-release
            type: File
        - name: vxflexos-config
          secret:
            secretName: vxflexos-config
        - name: vxflexos-config-params
          configMap:
            name: vxflexos-config-params
---
# Source: csi-vxflexos/templates/controller.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vxflexos-controller
  namespace: vxflexos

spec:
  selector:
    matchLabels:
      name: vxflexos-controller
  replicas: 1
  template:
    metadata:
      labels:
        vg-snapshotter-enabled: "true"
        name: vxflexos-controller
    spec:
      affinity:
        nodeSelector:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - vxflexos-controller
            topologyKey: kubernetes.io/hostname
      serviceAccountName: vxflexos-controller
      containers:
        - name: attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
          imagePullPolicy: Always
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
          imagePullPolicy: Always
          args:
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=true"
            - "--volume-name-prefix=vgs"
            - "--volume-name-uuid-length=10"
            - "--leader-election=true"
            - "--timeout=120s"
            - "--v=5"
            - "--default-fstype=xfs"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: vg-snapshotter
          image: amaas-eos-mw1.cec.lab.emc.com:5036/vg-controller:master-latest
          imagePullPolicy: Always
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
          imagePullPolicy: Always
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=120s"
            - "--v=5"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
          imagePullPolicy: Always
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: driver
          image: "amaas-eos-mw1.cec.lab.emc.com:5036/csi-vxflexos:v2.0-latest"
          imagePullPolicy: Always
          command: [ "/csi-vxflexos.sh" ]
          args:
            - "--leader-election"
            - "--array-config=/vxflexos-config/config"
            - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
          env:
            - name: CSI_ENDPOINT
              value: /var/run/csi/csi.sock
            - name: X_CSI_MODE
              value: controller
            - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
              value: "false"
            - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
              value: "false"
            - name: SSL_CERT_DIR
              value: /certs
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
            - name: vxflexos-config
              mountPath: /vxflexos-config
            - name: vxflexos-config-params
              mountPath: /vxflexos-config-params
      volumes:
        - name: socket-dir
          emptyDir:
        - name: vxflexos-config
          secret:
            secretName: vxflexos-config
        - name: vxflexos-config-params
          configMap:
            name: vxflexos-config-params
---
# Source: csi-vxflexos/templates/csidriver.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
    name: csi-vxflexos.dellemc.com
spec:
    attachRequired: true
    podInfoOnMount: true
    volumeLifecycleModes:
    - Persistent
    - Ephemeral

