apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: powerflex-app
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nb950/git2k8s10min.git
    targetRevision: master
    path: git2k8s10min/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
