apiVersion: v1
data:
  config: W3sidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiUGFzc3dvcmQxMjMiLCJpbnRlbmRlZEVuZHBvaW50IjoiaHR0cHM6Ly8xMC4yNDcuMzguNDciLCJlbmRwb2ludCI6Imh0dHBzOi8vbG9jYWxob3N0Ojk0MDAiLCJzeXN0ZW1JRCI6IjRkNGEyZTVhMzYwODBlMGYiLCJpbnNlY3VyZSI6dHJ1ZSwiaXNEZWZhdWx0Ijp0cnVlfV0K
kind: Secret
metadata:
  name: karavi-authorization-config
  namespace: vxflexos
type: Opaque
